name: update website
run-name: send-dispatch

on:
  push:
    branches: ["main"]

jobs:
  send-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: AmeMeida/monitorias
          event-type: submodule-push
